// <auto-generated />
namespace ULABInventory.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCPUIdDevIdDatatypeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCPUIdDevIdDatatypeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201707250936301_AddCPUId&DevIdDatatypeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
