// <auto-generated />
namespace ULABInventory.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddQRPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddQRPath));
        
        string IMigrationMetadata.Id
        {
            get { return "202111021255135_AddQRPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
